### ISSUE TITLE
Когда новые треки выйдут?

### ISSUE THREAD

**Issue by lptnkv** [APT-EHOT/ImageSearchApp#1]
Автор обещал новые песни, но их нет. Когда они выйдут?

**Comment by lptnkv** [comment]
Не решено!!!

**Comment by eto-postironia** [comment]
новые треки выпускают те, у кого старые плохие

**Comment by lptnkv** [comment]
![image](https://github.com/eto-postironia/ImageSearchApp/assets/61049065/0a0b1cfa-a41c-4d8b-a70c-5513ceb486f1)

**Comment by Kseyko** [comment]
Боже, я хуже кода не видел в своей жизни, я не представляю насколько автор неадекватен и просто ужасен в программировании. Еще и ник просто неадекватный. Будто бы придумал его великовозрастный ребенок солнца, которого так в детстве напекло, а на голову упала целая луна.
